# AUTOGENERATED! DO NOT EDIT! File to edit: l2_deploy.ipynb.

# %% auto 0
__all__ = ['temp', 'learn', 'categories', 'image', 'label', 'examples', 'inft', 'classifyImg']

# %% l2_deploy.ipynb 2
import fastai
from fastai.vision.all import *
import gradio as gr

#necessary trick to get around Linux path issues
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath

# %% l2_deploy.ipynb 5
learn=load_learner('l2_model.pkl') #compressed file stored in local dir


# %% l2_deploy.ipynb 7
categories=("Dog", "Cat")

def classifyImg(img):
    pred, idx, prob = learn.predict(img)
    return dict (zip(categories, map(float,prob))) #convert tensor to float for Gradio functionality

classifyImg(im)

# %% l2_deploy.ipynb 8
image=gr.inputs.Image()
label=gr.outputs.Label()
examples=['grizzly.jpg','pupper.jpg','cate.jpg']

inft=gr.Interface(fn=classifyImg, inputs=image, outputs=label, examples=examples)
inft.launch()
